language: haskell

ghc:
 - "7.10.3"
 - "8.0.2"
 - "8.2.2"
 - "8.4.4"
 - "8.6.3"

sudo: false

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

before_install:
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal update

script:
  - cabal new-build

notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
    skip_join: true
  email: true
